// lexicon/greekmandell_registry.js
// Greekmandell root and prefix registry for Phase 1 foundation
module.exports = {
  prefixes: {
    auto: { d: 'self', note: 'Greek self / autonomous' },
    poly: { d: 'many', note: 'Greek plural / multiple' },
    tele: { d: 'far/distant', note: 'Greek distance / remote' },
    hydro: { d: 'water', note: 'Greek water / liquid' },
    psycho: { d: 'mind', note: 'Greek mind / inner state' },
    chrono: { d: 'time', note: 'Greek temporal / sequence' },
    crypto: { d: 'hidden', note: 'Greek secret / concealed' },
    philo: { d: 'love', note: 'Greek affinity / intent' },
    geo: { d: 'earth', note: 'Greek earth / ground' },
    arch: { d: 'chief/first', note: 'Greek first / principal' },
    neo: { d: 'new', note: 'Greek new / novel' },
    para: { d: 'beside', note: 'Greek beside / parallel' },
    hypo: { d: 'under', note: 'Greek below / pressure low' },
    hyper: { d: 'over', note: 'Greek above / excess' },
    meta: { d: 'beyond/change', note: 'Greek beyond / transformation' },
    hypo: { d: 'under/below', note: 'Greek lower / beneath' },
    pan: { d: 'all', note: 'Greek whole / complete' },
  },
  roots: {
    log: { d: 'word/speech', note: 'Greek logic / speech' },
    phon: { d: 'sound', note: 'Greek sound / audio' },
    graph: { d: 'write/record', note: 'Greek record / form' },
    morph: { d: 'form', note: 'Greek shape / structure' },
    path: { d: 'suffering/feeling', note: 'Greek emotion / sensation' },
    tech: { d: 'skill/craft', note: 'Greek art / craft' },
    theo: { d: 'god', note: 'Greek divine / authority' },
    anthrop: { d: 'human', note: 'Greek human / person' },
    bio: { d: 'life', note: 'Greek life / biology' },
    demos: { d: 'people', note: 'Greek people / group' },
    ast: { d: 'star', note: 'Greek cosmic / light' },
    heli: { d: 'sun', note: 'Greek solar / radiant' },
    trop: { d: 'turn', note: 'Greek change / shift' },
    therm: { d: 'heat', note: 'Greek thermal / energy' },
    meter: { d: 'measure', note: 'Greek measurement / scale' },
    polis: { d: 'city', note: 'Greek city / system' },
    nom: { d: 'law', note: 'Greek rule / order' },
    od: { d: 'path', note: 'Greek way / journey' },
    crypt: { d: 'hidden', note: 'Greek secret / conceal' },
    xeno: { d: 'foreign', note: 'Greek stranger / other' },
  },
  suffixes: {
    ics: { d: 'study of', note: 'Greek discipline / domain' },
    logy: { d: 'study of', note: 'Greek science / system' },
    phile: { d: 'lover of', note: 'Greek affinity / preference' },
    phobia: { d: 'fear of', note: 'Greek aversion / resistance' },
    cracy: { d: 'rule by', note: 'Greek governance / system' },
    ist: { d: 'person who', note: 'Greek agent / profession' },
    ism: { d: 'belief/system', note: 'Greek ideology / practice' },
    oid: { d: 'resembling', note: 'Greek likeness / form' },
    ous: { d: 'full of', note: 'Greek abundance / descriptive' },
    ary: { d: 'relating to', note: 'Greek pertaining / associative' },
  },
};